name: A-Caller workflow
on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  deploy-ghost-part-category-mapping-to-endeca:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}    
    steps:
      - name: Dummy step
        run: echo Dummy
      - name: Exit
        run: |
          if [[ ${{ matrix.runner }} == 'ubuntu-latest']]; then
            exit 1
          else
            echo "Dummy"
          fi
          
        
  slack-post:
    needs: deploy-ghost-part-category-mapping-to-endeca
    if: ${{ !cancelled() }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/A-delete-2.yml
    with:
      slack_message: "${{ matrix.runner }} Deploy Ghost Part Category Mapping to Endeca"
      workflow_status: "${{ needs.deploy-ghost-part-category-mapping-to-endeca.result }}"
      runner: ${{ matrix.runner }}
















# jobs:
#   matrix-job:
#     strategy:
#       matrix:
#         runner: [ubuntu-latest, windows-latest]
#     runs-on: ${{ matrix.runner }}
#     steps:
#       - name: Print matrix
#         run: |
#           echo "Print matrix i.e, -> ${{ matrix.runner }}"
    
  
#   call-workflow:
#     needs: matrix-job
#     uses: ./.github/workflows/A-delete-2.yml
#     with:
#       slack_message: "${{ matrix.runner }} Deploy Ghost Part Category Mapping to Endeca"
