name: A-Caller workflow
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the App
        options:
          - 'nx-id'
          - 'nx-ole'
        default : 'nx-id'

jobs:
  deploy-ghost-part-category-mapping-to-endeca:
    # strategy:
    #   matrix:
    #     runner: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest    
    steps:
      - name: Dummy step
        id: dummy-step-1
        run: echo Dummy
      - name: Dummy step
        id: dummy-step-2
        run: exit 1
      - name: Dummy step
        if: steps.dummy-step-2.outcome == failure
        run: echo Dummy
      
          
        
  # slack-post:
  #   needs: deploy-ghost-part-category-mapping-to-endeca
  #   if: ${{ !cancelled() }}
  #   strategy:
  #     matrix:
  #       runner: [ubuntu-latest, windows-latest]
  #   uses: ./.github/workflows/A-delete-2.yml
  #   with:
  #     slack_message: "${{ matrix.runner }} Deploy Ghost Part Category Mapping to Endeca"
  #     workflow_status: "${{ needs.deploy-ghost-part-category-mapping-to-endeca.result }}"
  #     runner: ${{ matrix.runner }}
















# jobs:
#   matrix-job:
#     strategy:
#       matrix:
#         runner: [ubuntu-latest, windows-latest]
#     runs-on: ${{ matrix.runner }}
#     steps:
#       - name: Print matrix
#         run: |
#           echo "Print matrix i.e, -> ${{ matrix.runner }}"
    
  
#   call-workflow:
#     needs: matrix-job
#     uses: ./.github/workflows/A-delete-2.yml
#     with:
#       slack_message: "${{ matrix.runner }} Deploy Ghost Part Category Mapping to Endeca"
