name: A-Called workflow
on: 
  workflow_call:

jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get triggering user name
        if: always()
        id: triggered-by
        run: |
          TRIGGERED_BY=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ github.triggering_actor }} | grep -o '"name": *"[^"]*"' | sed 's/"name": "\(.*\)"/\1/')
          [ -z "$TRIGGERED_BY" ] && TRIGGERED_BY=${{ github.triggering_actor }}
          echo "TRIGGERED_BY=$TRIGGERED_BY" >> "$GITHUB_OUTPUT"
          
      - name: Print actor name
        run: echo ${{ steps.triggered-by.outputs.TRIGGERED_BY }}
