name: A Same name
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
        default : 'DEV'

  schedule:
    - cron: '50 12 * * *'   # PROD
jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
       - name: Dummy
         run: |
           echo "Input is ${{ inputs.environment }}"
           echo "Github event name is: ${{ github.event_name }}"

  uses-another:
    needs: empty
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/reusable-a-same-name.yml
    
