name: A Same name
on: workflow_dispatch
jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
       - name: Dummy
         run: echo "Dummy"

  uses-another:
    uses: ./.github/workflows/reusable-a-same-name.yml
    
