name: A Same name
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
        default : 'DEV'
jobs:
  empty:
    strategy:
      matrix:
        runner: [nx-id, nx-ole, nx-jlg]
    runs-on: ubuntu-latest
    environment: ${{ matrix.runner }}
    steps:
       - name: Dummy
         run: |
           echo "Input is ${{ inputs.environment }}"
           echo "Github event name is: ${{ github.event_name }}"

  uses-another:
    needs: empty
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/reusable-a-same-name.yml
    
