name: One job mulitple runner
on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       required: true
  #       type: choice
  #       description: Select the environment
  #       options:
  #         - 'Testing'
  #         - 'ole'
  #       default : 'Testing'
jobs:
  Runners:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: DEV or TEST runner
        run: |
          echo "${{ inputs.environment }}"
