name: Actor Schedule trigger
run-name: Schedule Actor
on: 
  schedule:
    - cron: '*/2 * * * *'

jobs:
  dev_job:
    name: Actor name
    runs-on: ubuntu-latest
    steps:
      - name: First Step for DEV
        run: echo "This is the first step for DEV"
