name: Branch protection Workflow
on: workflow_dispatch
  # workflow_run:
  #   workflows: ["Status-Check1"]
  #   types:
  #     - completed
jobs:
  onlyWhenCompleted:
    runs-on: ubuntu-latest
    steps:
      - name: Running first job
        run: echo "Running "

  set-commit-status:
    runs-on: ubuntu-latest
    steps:
       # - name: Create status check
       #   uses: actions/github-script@v4
       #   with:
       #    github-token: ${{ secrets.GITHUB_TOKEN }}
       #    script: |
       #      const context1 = github.context?.payload;
       #      const checks = context1?.checks;
       #      if (checks) {
       #        console.log("It has checks")
       #      }
       #      else {
       #        console.log('Checks object is undefined');
       #      }
      - name: Set commit status (success)
        env:
          GH_TOKEN: ${{ github.token }}
          GH_SHA: ${{github.sha}}
        run: |
          echo ${{ github.repository }}
          echo ${{github.sha}}
          echo $GH_SHA
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/commits/${{ github.sha }}/status

          
          # gh api repos/${{github.repository}}/statuses/${{github.sha}} -f state=success -f context='my-check'
          
          # curl -L \
          # -X POST \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # https://api.github.com/repos/${{github.repository}}/check-runs \
          # -d '{"name":"test","head_sha":"$GH_SHA","status":"completed","external_id":"42","output":{"title":"Test report","summary":"","text":""}}'
          
      #     curl -X POST \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
      #     -d '{"state": "success", "context": "custom-status-check", "description": "All checks passed!"}'

      # - name: Get check name
      #   run: |
      #     echo "Check name is ${{ github.event.check_suite.name }}"
      #     echo "check suite is ${{github.event.check_suite}}"
      #     echo "event is ${{github.event}}"
        
      # - name: Read Status
      #   run: |
      #     echo "Read"
      #     curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status

