name : Call a reusable workflow
on:
  workflow_dispatch:

jobs:
  job1:
    uses: Shivam26-2002/GithubActionsAssign/.github/workflows/ReusableWorkflow1.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run : echo ${{needs.job1.outputs.my-output}}
