name: Call Mulitple runner
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'ole'
        default : 'ole'
        
jobs:
  call_multiple_runner_job:
    runs-on: ubuntu-latest
    steps:
      
  
