name: CICD-1
on:
  workflow_dispatch:
    inputs:
      nx-Apps:
        required: true
        type: choice
        description: Select the App
        options:
          - 'nx-id'
          - 'nx-ole'
          - 'nx-jlg'
        default : 'nx-id'
jobs:
  check-affected-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: |
          sleep 30
          echo "Dummy step"

  build-and-deploy-id:
    if: ${{ (success('check-affected-projects') && inputs.nx-Apps == 'nx-id') }}
    needs: [check-affected-projects]
    uses: ./.github/workflows/project-cicd-1.yml
    with:
      environment: 'Testing'
    
  build-and-deploy-ole:
    if: ${{ (success('check-affected-projects') && inputs.nx-Apps == 'nx-ole') }}
    needs: [check-affected-projects]
    uses: ./.github/workflows/project-cicd-1.yml
    with:
      environment: 'ole'
    
  build-and-deploy-jlg:
    if: ${{ (success('check-affected-projects') && inputs.nx-Apps == 'nx-jlg') }}
    needs: [check-affected-projects]
    uses: ./.github/workflows/project-cicd-1.yml
    with:
      environment: 'jlg'

  send-slack-message-failure-check-affected-projects: 
    runs-on: ubuntu-latest
    # if: ${{ failure('check-affected-projects') }}  
    if: ${{ cancelled() || failure('check-affected-projects') }}
    needs: [check-affected-projects]
    steps:
      - name: Failure of check affected step
        run: echo "Failure of check affected step or cancelled"

  # send-slack-message-cancelled:
  #   runs-on: ubuntu-latest
  #   if: ${{ cancelled() }} 
  #   needs: [check-affected-projects,build-and-deploy-id,build-and-deploy-ole,build-and-deploy-jlg]
  #   steps:
  #     - name: Cancel step
  #       run: echo "Cacelled"
