name: CICD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Store build result
        id: build_result
        run: echo "::set-output name=build_result::$?"
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload
        run: make upload
      - name: Store upload result
        id: upload_result
        run: echo "::set-output name=upload_result::$?"
  process:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Process
        run: make process
      - name: Store process result
        id: process_result
        run: echo "::set-output name=process_result::$?"
  result:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Print result
        run: |
          echo "Build result: ${{ job.outputs.build_result }}"
          echo "Upload result: ${{ job.outputs.upload_result }}"
          echo "Process result: ${{ job.outputs.process_result }}"
