name: Conditional Checkout
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'nx-id'
          - 'TEST'
          - 'Testing'
        default : 'nx-id'
  push:

jobs:
  Env-Protection:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && 'dev' || github.ref_name }}
          
      - name: Dummy
        run: echo "Dummy workflow"

      - name: Print branch name
        run: echo ${{ github.ref_name }}
