name: Conditional Environment
run-name: >-
  ${{ (github.event_name == 'workflow_dispatch' && format('Push Schematics From Build Server - DEV'))
            || 
      (github.event_name == 'schedule' && (startsWith(github.event.schedule, '54 10') || startsWith(github.event.schedule, '04 11'))
          && format('Push Schematics From Build Server - TEST'))
            ||
      (github.event_name == 'schedule' && startsWith(github.event.schedule, '13 11') && format('Push Schematics From Build Server - PROD')) 
    }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '54 10 * * *'   # TEST
    - cron: '04 11 * * *'   # TEST
    - cron: '13 11 * * *'   # PROD
    
jobs:
  Conditional-Environment:
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'workflow_dispatch' && 'Testing') || 
                     (github.event_name == 'schedule' && 
                       (
                          ((startsWith(github.event.schedule, '32 9') || startsWith(github.event.schedule, '42 9')) && 'ole') || 
                          (startsWith(github.event.schedule, '52 9') && 'jlg')
                       ))
                  }}
    steps:
      - name: Dummy step
        run: |
          echo "Dummy"


          


# environment: ${{ github.event_name == 'workflow_dispatch' && 'Testing' || (github.event_name == 'schedule' && (startsWith(github.event.schedule, '10 8') || startsWith(github.event.schedule, '20 8'))) && 'ole' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '25 8')) && 'jlg' }} 
# inputs:
#       Environment:
#         required: true
#         type: choice
#         description: Select the environment
#         options:
#           - 'Testing'
#           - 'ole'
#         default : 'Testing'
