name: Conditional Environment
# run-name: >-
#   ${{ ( env.SCHEDULE_DEV == 'workflow_dispatch' && format('Push Schematics From Build Server - DEV,  env.SCHEDULE_TEST'))
#             || 
#       (github.event_name == 'schedule' && (startsWith(github.event.schedule, '${{ env.SCHEDULE_TEST }}') || startsWith(github.event.schedule, '${{ env.SCHEDULE_TEST_NEW }}'))
#           && format('Push Schematics From Build Server - TEST'))
#             ||
#       (github.event_name == 'schedule' && startsWith(github.event.schedule, '${{ env.SCHEDULE_PROD }}') && format('Push Schematics From Build Server - PROD')) 
#     }}
    
# run-name: >-
#   ${{ (github.event_name == 'workflow_dispatch' && format('Push Schematics From Build Server - DEV,  env.SCHEDULE_TEST'))
#             || 
#       (github.event_name == 'schedule' && (startsWith(github.event.schedule, '${{ env.SCHEDULE_TEST }}') || startsWith(github.event.schedule, '${{ env.SCHEDULE_TEST_NEW }}'))
#           && format('Push Schematics From Build Server - TEST'))
#             ||
#       (github.event_name == 'schedule' && startsWith(github.event.schedule, '${{ env.SCHEDULE_PROD }}') && format('Push Schematics From Build Server - PROD')) 
#     }}

on: 
  workflow_dispatch:
  # schedule:
    # - cron: '55 14 * * *'   # TEST
    # - cron: '05 15 * * *'   # TEST
    # - cron: '11 15 * * *'   # PROD
    
jobs:
  Conditional-Environment:
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'workflow_dispatch' && 'Testing') || 
                     (github.event_name == 'schedule'
                               && 
                       (
                          ((startsWith(github.event.schedule, '23 11') || startsWith(github.event.schedule, '33 11')) && 'ole') 
                                || 
                          (startsWith(github.event.schedule, '43 11') && 'jlg')
                       ))
                  }}
    steps:
      - name: Dummy step
        run: |
          echo "Dummy"
          echo "Print schedule DEV"
          echo ${{ env.SCHEDULE_DEV }}


          


# environment: ${{ github.event_name == 'workflow_dispatch' && 'Testing' || (github.event_name == 'schedule' && (startsWith(github.event.schedule, '10 8') || startsWith(github.event.schedule, '20 8'))) && 'ole' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '25 8')) && 'jlg' }} 
# inputs:
#       Environment:
#         required: true
#         type: choice
#         description: Select the environment
#         options:
#           - 'Testing'
#           - 'ole'
#         default : 'Testing'
