name: Conditional Environment
on: 
  workflow_dispatch:
  schedule:
    - cron: '32 9 * * *'   # TEST
    - cron: '42 9 * * *'   # TEST
    - cron: '52 9 * * *'   # PROD
    
jobs:
  Conditional-Environment:
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'workflow_dispatch' && 'Testing') || 
                     (github.event_name == 'schedule' && 
                       (
                          ((startsWith(github.event.schedule, '32 9') || startsWith(github.event.schedule, '42 9')) && 'ole') || 
                          (startsWith(github.event.schedule, '52 9') && 'jlg')
                       )
                      )
                  }}
    steps:
      - name: Dummy step
        run: |
          echo "Dummy"


          


# environment: ${{ github.event_name == 'workflow_dispatch' && 'Testing' || (github.event_name == 'schedule' && (startsWith(github.event.schedule, '10 8') || startsWith(github.event.schedule, '20 8'))) && 'ole' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '25 8')) && 'jlg' }} 
# inputs:
#       Environment:
#         required: true
#         type: choice
#         description: Select the environment
#         options:
#           - 'Testing'
#           - 'ole'
#         default : 'Testing'
