name: condition 
on:  
  push:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Ternary condtional set output
        id: set-environment
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo $BRANCH_NAME
          if [[ $BRANCH_NAME == release-* || $BRANCH_NAME == hotfix-* ]]; then
            if [[ $BRANCH_NAME == 'hotfix-2' ]]; then
              echo "Hotfix branch"
            fi
            echo "Release branch or hotfix branch"
            echo $BRANCH_NAME
          fi
          echo "DEPLOYMENT_ENVIRONMENT=$( test $BRANCH_NAME == 'main' && echo 'production' || echo 'preview')" >> "$GITHUB_OUTPUT"
        
      - name: Print output
        run: echo ${{ steps.set-environment.outputs.DEPLOYMENT_ENVIRONMENT }}
    
      - name: Deploy Sitemap
        id: deploy-sitemap
        run: | 
          sh "/apps/scripts/$(echo "${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]') /publish-sitemaps.sh"
        shell: bash 

      - name: Debug step print outcome of deploy sitemap step
        if: always()
        run: echo "${{ steps.deploy-sitemap.outcome }}"

      - name: Debug condition
        if: ${{ failure() && steps.deploy-sitemap.outcome == 'failure' }}
        run: echo "Worked"
        
      - name: Debug again step print outcome of deploy sitemap step
        if: ${{ steps.trial.outcome == 'failure' }}
        run: echo "Worked"
        
      - name: Trial step
        id: trial
        run: |
          echo "Trial job"

      - name: Failure step
        run: exit 1
        
      - name: Imp step
        id: trial1
        if: ${{ failure() && steps.trial.outcome == 'failure' }}
        run: |
          echo "Something"
          echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
          
      - name: Imp second step
        id: trial2
        if: always()
        # if: steps.trial.outcome == 'success' && steps.trial1.outcome == 'success'
        run: |
          echo ${{ steps.trial.outcome }}
          # echo "Success"
          
      - name: Imp third step
        if: steps.trial.outcome == 'success' || steps.trial1.outcome == 'success' || steps.trial2.outcome == 'success'
        run: echo "Final success"
