name: Conditional Environment
run-name: >-
  ${{ (github.event_name == 'workflow_dispatch' && format('Push Schematics From Build Server - DEV'))
            || 
      (github.event_name == 'schedule' && (startsWith(github.event.schedule, '23 11') || startsWith(github.event.schedule, '33 11'))
          && format('Push Schematics From Build Server - TEST'))
            ||
      (github.event_name == 'schedule' && startsWith(github.event.schedule, '43 11') && format('Push Schematics From Build Server - PROD')) 
    }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '23 11 * * *'   # TEST
    - cron: '33 11 * * *'   # TEST
    - cron: '43 11 * * *'   # PROD
    
jobs:
  Conditional-Environment:
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'workflow_dispatch' && 'Testing') || 
                     (github.event_name == 'schedule'
                               && 
                       (
                          ((startsWith(github.event.schedule, '23 11') || startsWith(github.event.schedule, '33 11')) && 'ole') 
                                || 
                          (startsWith(github.event.schedule, '43 11') && 'jlg')
                       ))
                  }}
    steps:
      - name: Dummy step
        run: |
          echo "Dummy"


          


# environment: ${{ github.event_name == 'workflow_dispatch' && 'Testing' || (github.event_name == 'schedule' && (startsWith(github.event.schedule, '10 8') || startsWith(github.event.schedule, '20 8'))) && 'ole' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '25 8')) && 'jlg' }} 
# inputs:
#       Environment:
#         required: true
#         type: choice
#         description: Select the environment
#         options:
#           - 'Testing'
#           - 'ole'
#         default : 'Testing'
