name: Conditional Slack message
run-name: >-
  ${{ (github.event_name == 'workflow_dispatch' && format('Conditional Slack message - DEV'))
            || 
      (github.event_name == 'schedule' && startsWith(github.event.schedule, '*/10') && format('Conditional Slack message - TEST'))
            ||
      (github.event_name == 'schedule' && startsWith(github.event.schedule, '*/15') && format('Conditional Slack message - PROD')) 
    }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '*/15 * * * *'

jobs:
  dev_job:
    name: Actor name
    runs-on: ubuntu-latest
    steps:
      - name: Push Schematics From Build Server - DEV
        id: build-dev
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "DEV step"
        
      - name: Push Schematics From Build Server - TEST
        id: build-test
        if: github.event_name == 'schedule' && (startsWith(github.event.schedule, '*/10'))
        run: |
         echo "TEST step"

      - name: Push Schematics From Build Server - PROD
        id: build-prod
        if: github.event_name == 'schedule' && (startsWith(github.event.schedule, '*/15'))
        run: |
          echo "PROD step"
          exit 1

      - name: Set Environment to display in slack message
        id: set-environment
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            ENVIRONMENT="DEV" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == 'schedule' ]]; then
            if [[ "${{ github.event.schedule }}" == '*/10 * * * *' ]]; then
              echo "ENVIRONMENT=TEST" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.schedule }}" == '*/15 * * * *' ]]; then
              echo "ENVIRONMENT=PROD" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Print slack Successful message
        if: ${{ always() && ( steps.build-dev.outcome != 'failure' && steps.build-test != 'failure' && steps.build-prod.outcome != 'failure' ) }}
        run: |
          echo "${{ steps.set-environment.outputs.ENVIRONMENT }}"
          echo "Successful message"
          
      - name: Print slack Failure message
        if: ${{ failure() && ( steps.build-dev.outcome == 'failure' || steps.build-test == 'failure' || steps.build-prod.outcome == 'failure' ) }}
        run: |
          echo "${{ steps.set-environment.outputs.ENVIRONMENT }}"
          echo "Failure message"
