name: Date and Time and Job status
on: workflow_dispatch
jobs:
  dateAndTime:
    runs-on: ubuntu-latest
    steps:
      - name: Date and time UTC
        run: |
          utc_time_formatted=$(date -u +"%d %b at %l:%M %p")
          echo "Current UTC time (formatted): $utc_time_formatted"
          exit 1

  Job-status-print:
    runs-on: ubuntu-latest
    if: always()
    needs: dateAndTime
    steps:
      - name: Job status
        run: |
          echo ${{ needs.dateAndTime.result }}
