name: Endeca Sitemap Generator
run-name: >-
  ${{ (inputs.environment == 'DEV' && format('Endeca Sitemap Generator - DEV'))
            || 
      (inputs.environment == 'TEST' && format('Endeca Sitemap Generator - TEST'))
            ||
      format('Endeca Sitemap Generator - PROD')
    }}
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'ubuntu-latest'
          - 'TEST'
        default : 'ubuntu-latest'
  push:
    
jobs:
  run-sitemap-generator:
    runs-on: [ "${{ inputs.environment || 'windows-latest' }}" ]
    steps:
      - name: Dummy step
        run: echo "Dummy "
        
  move-generated-sitemap:
    runs-on: [ "${{ inputs.environment || 'windows-latest' }}" ]
    needs: run-sitemap-generator
    steps:
      - name: Dummy step
        run: echo "Dummy step"
      - name: Move Generated Sitemap
        run: |
          if [[ "${{ inputs.environment }}" == "DEV" ]]; then
            ENV="DEV"
          elif [[ "${{ inputs.environment }}" == "TEST" ]]; then
            ENV="TEST"
          else
            ENV="PROD"
          fi
          echo "Environment is $ENV"
