name: A (Alphabet's)
run-name: >-
  ${{ inputs.environment && format('Endeca Sitemap Generator - {0}', inputs.environment )
            ||
      format('Endeca Sitemap Generator - PROD')
    }}
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
        default : 'DEV'
  schedule:
    - cron: '* * * * *'   # PROD
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        env:
          MY_ENV_VARIABLE: ${{ secrets.TEST_ENV }}
        run: |
          echo "Environment variable : ${{ vars.TEST_ENV }}."
          echo "Environment variable : $env.MY_ENV_VARIABLE"
          echo "Environment variable : $MY_ENV_VARIABLE"
