name: A (Alphabet's)
run-name: UX Translations (OCID's) - ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
          - 'PROD'
        default : 'DEV'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        env:
          MY_ENV_VARIABLE: ${{ secrets.TEST_ENV }}
        run: |
          echo "Environment variable : ${{ vars.TEST_ENV }}."
          echo "Environment variable : $env.MY_ENV_VARIABLE"
          echo "Environment variable : $MY_ENV_VARIABLE"
