name: Delete Branch using api
on: 
  push:
  workflow_dispatch:
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/new-dev"
            
      - name: Create dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{
              "ref": "refs/heads/DEV",
              "sha": "${{ github.sha }}"
            }'

      - name: Run if dev branch is being pushed
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's#refs/heads/##' -e 's/[^[:alnum:]-]/-/g')
          if [[ $BRANCH_NAME == 'DEV' ]]; then
            echo "Dev branch updated"
          else
            echo "Not a dev branch"
          fi
