name: A
on: 
  workflow_dispatch:
  push:
jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Test Results
        id: extract-report
        if: always()
        run: |
           echo "Worked" 
           
      - name: Print Test Report To Summary
        id: print-report
        if: steps.extract-report.outcome == 'success'
        run: |
             echo "## Test Results" >> $GITHUB_STEP_SUMMARY
             exit 1
             
      - run: echo "OK"
        if: job.steps.bad.status == failure()
