name: A
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'Testing'
          - 'ole'
          - 'ubuntu-latest'
        default : 'DEV'
  push:
jobs:
  D:
    runs-on: "${{ inputs.environment || 'windows-latest' }}" 
    # environment:  ${{ ((inputs.environment == 'Testing' || inputs.environment == 'ole') && 'Testing') || 'jlg' }}
    steps:
      - name: Extract Test Results
        id: extract-report
        run: |
          if [[ '${{github.event_name}}' == 'workflow_dispatch' ]]; then
            echo "Worked"
          else
            echo "PUSH"
          fi 
          
           
