name: Delete Branch using api
on: workflow_dispatch
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/workflow-test"
