name: A (Alphabet's)
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        run: |
          echo "Environment variable : ${{ env.TEST_ENV }}"
          echo "Environment variable : $env.TEST_ENV"
          echo "Environment variable : $TEST_ENV"
