name: A
on: 
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Do not select main branch'
jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - name: See what happens
        run: echo "Test"
