name: A (Alphabet's)
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variable
        env:
          MY_ENV_VARIABLE: ${{ secrets.TEST_ENV }}
        run: |
          echo "Environment variable : ${{ env.MY_ENV_VARIABLE }}"
          echo "Environment variable : $env.MY_ENV_VARIABLE"
          echo "Environment variable : $MY_ENV_VARIABLE"
