name: A
on: 
  workflow_dispatch:
  push:
jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - name: Print Random
        run: |
          url="https://nx-pawley93n-advanced-digital-solutions.vercel.app"
          cleaned_url=$(echo "$url" | sed 's/^https:\/\///')
          echo "$cleaned_url"

      - name: Set Environment
        id: set-environment
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo ${{ github.event_name }}
          if [[ $BRANCH_NAME == 'main' && ${{ github.event_name }} == 'push' ]]; then
            echo "DEPLOYMENT_ENVIRONMENT=production" >> "$GITHUB_OUTPUT"
          else
            echo "DEPLOYMENT_ENVIRONMENT=preview" >> "$GITHUB_OUTPUT"
          fi
      - name: Print Deployment Environment
        run: echo ${{ steps.set-environment.outputs.DEPLOYMENT_ENVIRONMENT }}
