name: A
on: 
  workflow_dispatch:
jobs:
  D:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: See what happens
        id: test-output
        run: echo "ALIAS=Test" >> "$GITHUB_OUTPUT" >> $GITHUB_STEP_SUMMARY

      - name: Print output
        run: |
          echo ${{ steps.test-output.outputs.ALIAS }}
