name: A
on: 
  workflow_dispatch:
jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - name: See what happens
        id: test-output
        run: echo "ALIAS=Test" >> $GITHUB_STEP_SUMMARY >> "$GITHUB_OUTPUT"

      - name: Print output
        run: |
          echo ${{ steps.test-output.outputs.ALIAS }}
