name: A
on: 
  workflow_dispatch:
jobs:
  D:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment
        id: set-environment
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [ $BRANCH_NAME != 'main' ]; then
            echo "DEPLOYMENT_ENVIRONMENT=production" >> "$GITHUB_OUTPUT"
          else
            echo "DEPLOYMENT_ENVIRONMENT=preview" >> "$GITHUB_OUTPUT"
          fi
      - name: Print Deployment Environment
        run: echo ${{ steps.set-environment.outputs.DEPLOYMENT_ENVIRONMENT }}
