name: Download logs
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Trial step
        run: echo "Hello world"
          # GH_TOKEN: ${{ github.token }}
      - name: Get GitHub context
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Token is: ${{ github.token }}"
          # gh run view ${{ github.run_id }} --log
      - name: Download logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN
          echo "Secret token: "
          echo "${{ secrets.GITHUB_TOKEN }}"
          curl --request GET \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs
