name: Download logs
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Trial step
        run: echo "Hello world"
      - name: Get GitHub context
        env:
          GH_TOKEN: ${{ secrets.DOWNLOAD_LOGS }}
        run: |
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Token is: ${{ github.token }}"
          # gh run view ${{ github.run_id }} --log
      - name: Download logs
        run: |
          DOWNLOAD_TOKEN=${{ secrets.FINE_GRAINED_PAT }}
          echo "Secret token: "
          echo " Token is : $DOWNLOAD_TOKEN"
          echo "${{ secrets.FINE_GRAINED_PAT }}"
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $DOWNLOAD_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs
