name: Dynamic Runner
on:
  workflow_dispatch:
    inputs:
      dynamic_branch:
        description: Select branch
        required: true
        type: dynamic_branch
        default: main
jobs:
  Dynamic-Runner:
    runs-on: ubuntu-latest
    steps:
      - name: Test 
        run: echo "Run"
