name: Bounce Endeca Services
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  endeca-bounce-all-services:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Bounce Endeca Services
        id: bounce-endeca-services
        run: |
          echo "Done"
 
