name: Environment-testing-main
on: workflow_dispatch
jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      DEPLOYMENT_ENVIRONMENT: ${{ steps.set-environment.outputs.DEPLOYMENT_ENVIRONMENT }}
    steps:
      - name: Set Environment
        id: set-environment
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [ $BRANCH_NAME == 'main' ]; then
            echo "DEPLOYMENT_ENVIRONMENT=production" >> "$GITHUB_OUTPUT"
            echo "$DEPLOYMENT_ENVIRONMENT"
          else
            echo "DEPLOYMENT_ENVIRONMENT=preview" >> "$GITHUB_OUTPUT"
            echo "$DEPLOYMENT_ENVIRONMENT"
          fi
  
  job-will-use-workflow:
    uses: ./.github/workflows/Environment-testing.yml
    with:
      environment: ${{ if(needs.set-environment.outputs.DEPLOYMENT_ENVIRONMENT == 'production', 'Testing', 'staging-approver') }}

  slack-message:
    needs: [job-will-use-workflow]
    if: always()
    runs-on: ubuntu-latest
    outputs: 
      slack_workflow_name: ${{ steps.set-slack-workflow-name.outputs.slack_workflow_name }} 
    steps:
      - name: Set workflow name for slack message
        id: set-slack-workflow-name
        env:
          build_and_deploy_id_result: ${{ needs.job-will-use-workflow.result }}
          build_and_deploy_id_reviewed: ${{ needs.job-will-use-workflow.outputs.reviewed }}
        run: |
          echo $build_and_deploy_id_result
          echo $build_and_deploy_id_reviewed
          if [[ $build_and_deploy_id_result == 'failure' ]] && [[ $build_and_deploy_id_reviewed == 'true' ]]; then
            echo "slack_workflow_name=Build and Deploy ID" >> $GITHUB_OUTPUT
          elif [[ $build_and_deploy_id_result == 'failure' ]] && [[ $build_and_deploy_id_reviewed != 'true' ]]; then            
            echo "slack_workflow_name=Build and Deploy ID" >> $GITHUB_OUTPUT 
          elif [[ $build_and_deploy_id_result == 'cancelled' ]]; then            
           echo "slack_workflow_name=Build and Deploy ID" >> $GITHUB_OUTPUT
          fi

  slack-result:
    runs-on: ubuntu-latest
    # if: ${{ cancelled() || ( failure('job-will-use-workflow') && needs.job-will-use-workflow.outputs.reviewed != 'true') }}    
    if: ${{ cancelled() || ( failure('job-will-use-workflow') && needs.job-will-use-workflow.outputs.reviewed != 'true') }}    
    needs: [slack-message, job-will-use-workflow]
    steps:
      - name: Result step
        run: |
          echo Cancelled approval ${{ needs.slack-message.outputs.slack_workflow_name }}
          echo ${{ needs.job-will-use-workflow.outputs.reviewed }}
    
