name: Environment Testing
on: workflow_call
jobs:
  wait_for_approval:    
    runs-on: ubuntu-latest
    environment: Testing   # approval environment
    outputs: 
      reviewed: ${{ steps.set-output-deployment.outputs.reviewed }}    
    steps:
    - name: Deployment approved
      id: set-output-deployment
      run: |
        echo 'Deployment approved'
        echo "reviewed=true" >> $GITHUB_OUTPUT

  cicd:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Dummy step
        run: echo "Hello World"
        
