name: Environment-testing-main
on: workflow_dispatch
jobs:
  job-will-use-workflow:
    uses: ./.github/workflows/Environment-testing.yml

  slack-message:
    needs: [job-will-use-workflow]
    if: always()
    runs-on: ubuntu-latest
    outputs: 
      slack_workflow_name: ${{ steps.set-slack-workflow-name.outputs.slack_workflow_name }} 
    steps:
      - name: Set workflow name for slack message
        id: set-slack-workflow-name
        env:
          build_and_deploy_id_result: ${{ needs.job-will-use-workflow.result }}
        run: |
          echo $build_and_deploy_id_result
          if [[ $build_and_deploy_id_result == 'failure' ]] && [[ $build_and_deploy_id_reviewed == 'true' ]]; then
            echo "slack_workflow_name=Build and Deploy ID" >> $GITHUB_OUTPUT
          elif [[ $build_and_deploy_id_result == 'failure' ]] && [[ $build_and_deploy_id_reviewed != 'true' ]]; then            
            echo "slack_workflow_name=Build and Deploy ID" >> $GITHUB_OUTPUT 
          fi

  slack-result:
    runs-on: ubuntu-latest
    if: ${{ cancelled() || ( failure('build-and-deploy-id')  &&  needs.build-and-deploy-id.outputs.reviewed != 'true') }}    
    needs: [slack-message, job-will-use-workflow]
    steps:
      - name: Result step
        run: |
          echo Cancelled approval ${{ needs.slack-message.outputs.slack_workflow_name }}
    
