name: Environment Testing
on: workflow_call
jobs:
  wait_for_approval:    
    runs-on: ubuntu-latest
    environment: Testing   # approval environment
    outputs: 
      reviewed: ${{ steps.set-output-deployment.outputs.reviewed }}    
    steps:
    - name: Deployment approved
      id: set-output-deployment
      run: |
        echo 'Deployment approved'
        echo "reviewed=true" >> $GITHUB_OUTPUT
        
  cicd:
    runs-on: ubuntu-latest
    environment: Testing
    outputs: 
      JOB-OUTPUT: ${{ steps.set-output.outputs.JOB-OUTPUT }}
    steps:
      - name: Dummy step
        run: echo "Hello World"
      - name: Set output of job
        id: set-output
        if: always()
        env:
         JOB_STATUS: ${{ job.status }}
        run: |
          echo "$JOB_STATUS"
          # exit 1
          echo "JOB-OUTPUT=$JOB_STATUS" >> "$GITHUB_OUTPUT"

  
  slack-failure:
    runs-on: ubuntu-latest
    needs: [cicd]
    if: always()
    steps:
      - name: Run slack failure
        run: |
          echo "${{ needs.cicd.outputs.JOB-OUTPUT }}"
        
