name: Extract Text
on: workflow_dispatch
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Test multi line string
        run: |
          multiline_string1='✔  cart.cy.tsx                              124ms        1        1        -        -        - │
          '
          echo "$multiline_string1"
