name: Extract Text
on: workflow_dispatch
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Test multi line string
        run: |
          mulit_line_string='(Run Finished)
               Spec                                              Tests  Passing  Failing  Pending  Skipped  
          ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
          │ ✖  base-breadcrumbs-pages.cy.ts             00:09        2        1        1        -        - │
          ├────────────────────────────────────────────────────────────────────────────────────────────────┤
          │ ✔  basic-test.cy.ts                          44ms        1        1        -        -        - │
          ├────────────────────────────────────────────────────────────────────────────────────────────────┤
          │ ✔  cookie-banner.cy.ts                      00:05        2        2        -        -        - │
          └────────────────────────────────────────────────────────────────────────────────────────────────┘
            ✖  1 of 3 failed (33%)                      00:15        5        4        1        -        - '
          echo "Printing log"
          echo "$mulit_line_string"

          
