name: Extract Text
on: workflow_dispatch
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Test multi line string
        run: |
          npm install fs
          node - <<EOF
            const fs = require('fs');
            const pattern1 = /\d+ms\s+\d+\s+\d+\s+-+\s+-+\s+-+/;
            const pattern2 = /(\d{2}:\d{2})\s+(\d+)\s+(\d+)\s+(-+)\s+(-+)\s+(-+)/;
            const pattern3 = /(\d+:\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(-+)\s+(-+)/;
            let pattern_removal;
            let matches_finall;
            lastLine = "✖  1 of 2 failed (50%)                      00:10        3        2        1        -        -"
            console.log(" Start IF condition ");
            if (pattern1.test(lastLine)) {
                matches_finall = lastLine.match(pattern1);
                pattern_removal = pattern1;
                console.log("Pattern1");
                console.log("Pattern to be used is:", pattern_removal)
            }
            else if(pattern2.test(lastLine)){
                matches_finall = lastLine.match(pattern2);
                pattern_removal = pattern2;
                console.log("Pattern2");
                console.log("Pattern to be used is:", pattern_removal)
            }
            else{
                matches_finall = lastLine.match(pattern3);
                pattern_removal = pattern2;
                console.log("Pattern3");
                console.log("Pattern to be used is:", pattern_removal)
            }
          EOF

    
