name: Github Context
on: workflow_dispatch
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Check case sensitive or not in shell script
        run: |
          if [ "Shivam" -eq "Shivam" ];then
            echo "Git case insensitive"
          else
            echo "Git case sensitive"
          fi
          
      - name: Check case sensitive or not
        if: ${{github.event.ref}} == "refs/heads/main"
        run: echo "Case Sensitive"
        
      - name: Check case sensitive or not 2
        if: ${{github.event.ref}} == "REFS/HEADS/MAIN"
        run: echo "Case In-Sensitive"
          
      - name: Write Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event.repository.archive_url}}"
          echo "$GITHUB_CONTEXT"

      - name: Write So
        run: echo  "${{github.event.ref}}"
          
      - name: Check condition
        if: ${{github.event.ref}} == "refs/heads/"
        run: echo "Not Working" 
        
      - name: Check condition
        if: ${{github.event.ref}} == "refs/heads/main"
        run: echo "Working" 

      - name: If else 
        run: |
           if [ "${{github.event.ref}}" == "refs/heads/" ];then
             echo "Not working"
           elif [ "${{github.event.ref}}" == "refs/heads/main" ];then
             echo " Working"
           else
            echo "Fook liya h"
           fi
         
        
      - name: Modifying branch name
        run: |
          replace_alnum_with_hyphen() {
          echo "$1" | sed -E 's/[^[:alnum:]]/-/g'
          }
          input_string="feature/O20R-123_test.test"
          converted_string=$(replace_alnum_with_hyphen "$input_string")
          echo "Original string: $input_string"
          echo "Converted string: $converted_string"
