name: Github Context
on: workflow_dispatch
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Remove whitespaces using xargs and [:space:]
        run: |
          WORD='Hello world'
          # echo -e "WORD='${WORD}'"
          ENV_URL= "$(echo -e "${WORD}" | tr -d '[:space:]')"
          # LOWERCASE_WORD="${ENV_URL,,}"
          echo $ENV_URL
          echo "LOWERCASE_WORD"
          echo "   lol  " | xargs
          FOO=' test test test '
          echo -e "FOO='${FOO}'"
          # > FOO=' test test test '
          echo -e "length(FOO)==${#FOO}"
          # > length(FOO)==16

          #  remove all whitespace (denoted by [:space:] in tr):
          FOO_NO_WHITESPACE="$(echo -e "${FOO}" | tr -d '[:space:]')"
          echo -e "FOO_NO_WHITESPACE='${FOO_NO_WHITESPACE}'"
          # > FOO_NO_WHITESPACE='testtesttest'
          echo -e "length(FOO_NO_WHITESPACE)==${#FOO_NO_WHITESPACE}"
          # > length(FOO_NO_WHITESPACE)==12

          # remove leading whitespace only:

          FOO_NO_LEAD_SPACE="$(echo -e "${FOO}" | sed -e 's/^[[:space:]]*//')"
          echo -e "FOO_NO_LEAD_SPACE='${FOO_NO_LEAD_SPACE}'"
          # > FOO_NO_LEAD_SPACE='test test test '
          echo -e "length(FOO_NO_LEAD_SPACE)==${#FOO_NO_LEAD_SPACE}"
          # > length(FOO_NO_LEAD_SPACE)==15

          # remove trailing whitespace only:

          FOO_NO_TRAIL_SPACE="$(echo -e "${FOO}" | sed -e 's/[[:space:]]*$//')"
          echo -e "FOO_NO_TRAIL_SPACE='${FOO_NO_TRAIL_SPACE}'"
          # > FOO_NO_TRAIL_SPACE=' test test test'
          echo -e "length(FOO_NO_TRAIL_SPACE)==${#FOO_NO_TRAIL_SPACE}"
          # > length(FOO_NO_TRAIL_SPACE)==15

          # remove both leading and trailing spaces--chain the seds:

          FOO_NO_EXTERNAL_SPACE="$(echo -e "${FOO}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          echo -e "FOO_NO_EXTERNAL_SPACE='${FOO_NO_EXTERNAL_SPACE}'"
          # > FOO_NO_EXTERNAL_SPACE='test test test'
          echo -e "length(FOO_NO_EXTERNAL_SPACE)==${#FOO_NO_EXTERNAL_SPACE}"
          # > length(FOO_NO_EXTERNAL_SPACE)==14

          
      - name: Check case sensitive or not in shell script
        run: |
          if [ "Shivam" == "shivam" ];then
            echo "Git case insensitive"
          else
            echo "Git case sensitive"
          fi
          
      - name: Check case sensitive or not
        if: ${{github.event.ref}} == "refs/heads/main"
        run: echo "Case Sensitive"
        
      - name: Check case sensitive or not 2
        if: ${{github.event.ref}} == "REFS/HEADS/MAIN"
        run: echo "Case In-Sensitive"
          
      - name: Write Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event.repository.archive_url}}"
          echo "$GITHUB_CONTEXT"

      - name: Write So
        run: echo  "${{github.event.ref}}"
          
      - name: Check condition
        if: ${{github.event.ref}} == "refs/heads/"
        run: echo "Not Working" 
        
      - name: Check condition
        if: ${{github.event.ref}} == "refs/heads/main"
        run: echo "Working" 

      - name: If else 
        run: |
           if [ "${{github.event.ref}}" == "refs/heads/" ];then
             echo "Not working"
           elif [ "${{github.event.ref}}" == "refs/heads/main" ];then
             echo " Working"
           else
            echo "Fook liya h"
           fi
         
        
      - name: Modifying branch name
        run: |
          replace_alnum_with_hyphen() {
          echo "$1" | sed -E 's/[^[:alnum:]]/-/g'
          }
          input_name="feature/O20R-123_test.test"
          converted_name=$(replace_alnum_with_hyphen "$input_name")
          echo "Original name: $input_name"
          echo "Converted name: $converted_name"
