name: Github Context
on: workflow_dispatch
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Write Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{github.event_name}}"
          echo "${{github.event.repository.archive_url}}"
          echo "$GITHUB_CONTEXT"
      - name: Modifying branch name
        run: |
          replace_alnum_with_hyphen() {
          echo "$1" | sed -E 's/[^[:alnum:]]/-/g'
          }
          input_string="feature/O20R-123_test.test"
          converted_string=$(replace_alnum_with_hyphen "$input_string")
          echo "Original string: $input_string"
          echo "Converted string: $converted_string"
