name: Github Context
on: workflow_dispatch
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Write Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
