name : Hello World Workflow
on : workflow_dispatch
jobs:
  HelloJob:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}}
    steps:
      - name : Hello World output
        id : step1
        run: echo "test=hello world" >> $GITHUB_OUTPUT
      - name : Print Output
        run: echo ${{output1}}
