name : Input Types Workflow
on :
  workflow_dispatch:
    inputs:
      configuration:
        description: 'A string input'
        type: string
        required: true
        default: 'Hello'
      configcode:
        description: 'A number input'
        type: number
        required: false
        default: '10'
      configtype:
        description: 'Dropdown input'
        required: true
        type: choice
        options:
          - Staging
          - Prod
          - QA
        default : 'Prod'
jobs:
  WriteInput:
    runs-on: ubuntu-latest
    steps:
      - name : Print Number Inputs
        run: |
          if [ -z "${{ github.event.inputs.ConfigCode }}" ]; then
            echo "${{ github.event.inputs.configuration }}  ${{ github.event.inputs.configtype }}"
          else
            echo "${{ github.event.inputs.configuration }}  ${{ github.event.inputs.configcode }}  ${{ github.event.inputs.configtype }}"
          fi
        
        
