name : Input Types Workflow
on :
  workflow_dispatch:
    inputs:
      configcode:
        description: 'A number input'
        required: false
        default: '10'
        # type: number
jobs:
  WriteInput:
    runs-on: ubuntu-latest
    env:
      input_number:  ${{github.event.inputs.configcode}}
    steps:
      - name : Print Number Inputs
        run : echo "$env.input_number"
        
        
