name : Input Types Workflow
on :
  workflow_dispatch:
    inputs:
      configcode:
        description: 'A number input'
        required: false
        default: '10'
        # type: number
jobs:
  WriteInput:
    runs-on: ubuntu-latest
    steps:
      - name : Print Number Inputs
        env:
         input_number: ${{github.event.inputs.configcode}}
        run : echo "$input_number"
        
        
