name : Input Types Workflow
on :
  workflow_dispatch:
    inputs:
      Configuration:
        description: 'A string input'
        type: string
        required: true
        default: 'Hello'
      ConfigCode:
        description: 'A number input'
        required: false
        default: '10'
      ConfigType:
        description: 'Dropdown input'
        required: true
        type: choice
        options:
          - Staging
          - Prod
          - QA
        default : 'Prod'
jobs:
  WriteInput:
    runs-on: ubuntu-latest
    # env:
    #   input_number:  ${{github.event.inputs.ConfigCode}}
    steps:
      - name : Print Another Inputs
        if : ${{github.event.inputs.ConfigCode == ''}}
        run : echo "${{github.event.inputs.Configuration}},${{github.event.inputs.ConfigType}} "
      - name : Print Inputs
        if: ${{github.event.inputs.ConfigCode}}
        run : echo " ${{github.event.inputs.Configuration}},${{github.event.inputs.ConfigCode}}, ${{github.event.inputs.ConfigType}}"
        
        
