name : Input Types Workflow
on :
  workflow_dispatch:
    inputs:
      Configuration:
        description: 'A string input'
        type: string
        required: true
        default: 'Hello'
      ConfigCode:
        description: A string input
        required: false
        default: '10'
      ConfigType:
        description: 'Dropdown input'
        required: true
        type: choice
        options:
          - Staging
          - Prod
          - QA
        default : 'Prod'
jobs:
  WriteInput:
    runs-on: ubuntu-latest
    steps:
      - name : Print Inputs string
        run : echo " Hello ${{github.event.inputs.Configuration}}"
      - name : Print Input Dropdown
        run : echo "${{github.event.inputs.ConfigType}}"
      - name : Print Input Number
        run : echo "${{github.event.inputs.ConfigCode}}"
    
        
        
