name: job-status
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    outputs: 
      job_status: ${{ steps. job_id.outputs.job_status }}
    steps:
     - name: Fail step
       run: exit 1
     - name: Dump job context
       id: job_id
       if: always()
       env:
         JOB_STATUS: ${{ job.status }}
       run: |
         echo "$JOB_STATUS"
         echo "job_status=$JOB_STATUS" >> GITHUB_OUTPUT
  job-status-write:
    runs-on: ubuntu-latest
    steps:
     - name: Job output stataus
       if: always()
       run: echo ${{ jobs.my_job.outputs.job_status }}
  # my_next_job:
  #   runs-on: ubuntu-latest
  #   needs: my_job
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   run: |
  #     echo ${{}}

        
