name: job-status
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    outputs: 
      JOB_STATUS_WRITE: ${{ steps.job_id.outputs.JOB_STATUS_WRITE }}
    steps:
     - name: Fail step
       run: exit 1
     - name: Dump job context
       id: job_id
       if: always()
       env:
         JOB_STATUS: ${{ job.status }}
       run: |
         echo "$JOB_STATUS"
         echo "JOB_STATUS_WRITE=$JOB_STATUS" >> "$GITHUB_OUTPUT"
         echo "$JOB_STATUS_WRITE"
     - name: Write the job status
       if: always()
       run: |
         echo ${{ steps.job_id.outputs.JOB_STATUS_WRITE }}
  job-status-write:
    runs-on: ubuntu-latest
    needs: [my_job]
    if: always()
    steps:
     - name: Write the job status
       if: always()
       run: |
         echo ${{ steps.job_id.outputs.JOB_STATUS_WRITE }}
