name: job-status
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
     - name: Fail step
       run: exit 1
     - name: Dump job context
       if: always()
       env:
         JOB_STATUS: ${{ job.status }}
       run: |
         echo "$JOB_STATUS"
  # my_next_job:
  #   runs-on: ubuntu-latest
  #   needs: my_job
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   run: |
  #     echo ${{}}

        
