name: job-status
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
     - name: Fail step
       run: exit 1
     - name: Dump job context
       id: job-status-output
       if: always()
       env:
         JOB_STATUS: ${{ job.status }}
       run: |
         echo "job-status=$JOB_STATUS" >> GITHUB_OUTPUT
     - name: Job output stataus
       if: always()
       run: echo ${{ steps.job-status-output.outputs.job-status }}
  # my_next_job:
  #   runs-on: ubuntu-latest
  #   needs: my_job
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   run: |
  #     echo ${{}}

        
