name: job-status
on: workflow_dispatch
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Hello, world!"
  my_next_job:
    runs-on: ubuntu-latest
    needs: my_job
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Next Step
        run: echo "Next job runs only if the previous job succeeded."

        
