name: Workflow run 1
on:
  workflow_dispatch:
jobs:
  start1:
    runs-on: ubuntu-latest
    steps:
    - name: Write
      run: echo "Hello Workflow 1"
    - name: Write actor and branch
      run: echo "*By:* ${{ github.actor }} *Branch:* ${{ github.event.ref }}"
    - name: Get Short SHA
      id: setShortSha
      run: echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
    - name: Write SHA
      run: echo "*Short SHA:* ${{ steps.setShortSha.outputs.short_sha }}"
    - name: Write date
      run: echo "*Date:* $(date -d "${{ github.event.head_commit.timestamp }}" '+%Y-%m-%d')"
    - name: Write time
      run: echo "*Time:* $(date -d "${{ github.event.head_commit.timestamp }}" '+%H:%M')"

