name: Minify and Zip Workflow
on:
 workflow_dispatch:
jobs:
  minify-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Minify JS and CSS Files
        run: |
          mkdir -p minified
          npx terser .github/JS/1.js -o minified/minified.js
          
  create-zip:
    needs: minify-files
    runs-on: ubuntu-latest
    steps:
      - name: Archive Minified Files
        uses: montudor/action-zip@v0.2.1
        with:
          files: minified
          output-name: minified-files
      - name: Upload Minified Files
        uses: actions/upload-artifact@v2
        with:
          name: minified-files
          path: minified
