name: Minify files
on:
  workflow_dispatch:

jobs:
   minify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Minify JavaScript files
      uses: anthonyftwang/minify-action@v1.0.1
      with:
        directory: 'js'
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Minify JavaScript files
