name: Minify and Zip Workflow
on:
 workflow_dispatch:
jobs:
  minify-files:
    runs-on: ubuntu-latest
    steps:
     - name: Run Minify Action
       uses: juliansangillo/minify-action@v1
       with:
         minify_files: "/*.js"
         output_directory: "dist"

          
  # create-zip:
  #   needs: minify-files
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Archive Minified Files
  #       uses: vimtor/action-zip@v1.1
  #       with:
  #         files: minified
  #         output-name: minified-files
  #     - name: Upload Minified Files
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: minified-files
  #         path: minified


# jobs:
#   zip-files:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: vimtor/action-zip@v1.1
#         with:
#           files: dist/ manifest.json
#           dest: result.zip
