name: Multiple Trigger
on: 
  workflow_call:
  workflow_dispatch:
  push:  
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Run dummy step
        run: echo "Multiple trigger" 
