name: Multiple Trigger
on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'Testing'
          - 'DEV'
        default : 'Testing'
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    environment: ${{ inputs.call_environment == 'ole' && 'ole' || inputs.environment }}
    steps:
      - name: Run dummy step
        run: echo "Multiple trigger"

      - name: Print input
        run: |
          echo ${{ inputs.call_environment }}

      - name: Print event name
        run: |
          echo ${{ github.event_name }}

      - name: Check Trigger Event
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "This workflow was triggered by a workflow_dispatch event."
          elif [ "${{ github.event_name }}" == "workflow_call" ]; then
            echo "This workflow was triggered by a workflow_call event."
          else
            echo "Unknown trigger event."
          fi
