name: Call multiple trigger workflow
on:
  workflow_dispatch:
    inputs:
        environment:
          required: true
          type: choice
          description: Select the environment
          options:
            - 'ole'
          default : 'ole'
jobs:
  call-multiple-trigger-workflow:
    uses: ./.github/workflows/multiple_trigger.yml
    with:
      environment: ${{ inputs.call_environment }}
