name: PROJECT CICD-1
on: 
 workflow_call:
    inputs:
      environment:
        type: string

jobs:
  wait_for_approval:    
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs: 
      reviewed: ${{ steps.set-output.outputs.reviewed }}    
    steps:
    - name: Deployment approved
      id: set-output
      run: |
        echo 'Deployment approved'
        echo "reviewed=true" >> $GITHUB_OUTPUT
    
  cicd:
    runs-on: ubuntu-latest
    needs: [wait_for_approval]
    steps:
      - name: Dummy cicd
        run: echo "cicd"

  slack-success-failure:
    runs-on: ubuntu-latest
    needs: [wait_for_approval, cicd]
    if: ${{ ( success('cicd') && needs.wait_for_approval.outputs.reviewed == 'true' ) || ( failure('cicd') && needs.wait_for_approval.outputs.reviewed == 'true' ) }}
    steps:
      - name: Print success or failure
        run: echo "Success or failure"

  slack-rejected:
    runs-on: ubuntu-latest
    needs: [wait_for_approval]
    if: ${{ always() && needs.wait_for_approval.outputs.reviewed != 'true' }}
    steps:
       - name: Print rejected
         run: echo "Rejected"
