name: PROJECT CICD-1
on: 
 workflow_call:
    inputs:
      environment:
        type: string
    outputs:
      REVIEWED:
        description: "Output to check if the job was approved"
        value: ${{ jobs.cicd.outputs.reviewed }}

jobs:    
  cicd:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs: 
      reviewed: ${{ steps.set-output.outputs.reviewed }}  
    steps:
      - name: Dummy cicd
        run: |
         echo "reviewed=true" >> $GITHUB_OUTPUT
         echo "cicd"

  slack-success-failure:
    runs-on: ubuntu-latest
    needs: [cicd]
    if: ${{ ( success('cicd') && needs.cicd.outputs.reviewed == 'true' ) || ( failure('cicd') && needs.cicd.outputs.reviewed == 'true' ) }}
    steps:
      - name: Print success or failure
        run: echo "Success or failure"

  slack-rejected:
    runs-on: ubuntu-latest
    needs: [cicd]
    if: ${{ always() && needs.cicd.outputs.reviewed != 'true' }}
    steps:
       - name: Print rejected
         run: echo "Rejected"
