name : Pull Request Workflow
on:
  pull_request:
    types:
      - opened
jobs:
  checkPull:
    runs-on: ubuntu-latest
    steps:
    - name : Before If condition
      run: echo ${{github.event.pull_request.base.ref}}
    - name : Check if branch name is right or not
      run : |
        if[[ ${{github.event_name}} == 'pull_request' && ( ${{ github.event.pull_request.base.ref}} =~ ^release-.*$|^fix-.*$ )]]
          echo "Running workflow for release or fix branch"
        else
          echo " Not running workflow for this branch"
          exit 0
        fi




        
