name : Pull Request Workflow Test
on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.pull_request.base.ref}}
    # if: ${{ github.event.pull_request.base.ref == 'release-*' || github.event.pull_request.base.ref == 'fix-*' }} 
    # steps:
    #   - run: echo "Hello, World!"
