name : Pull Request Workflow
on:
  pull_request:
    types:
      - opened
jobs:
  checkPull:
    runs-on: ubuntu-latest
    steps:
    - name : Before If condition
      run: echo ${{github.event.pull_request.base.ref}}
    - name: After IF condition
      if: contains('release-', github.event.pull_request.base.ref)
      run : echo "Run pull request"




        
