name : Pull Request Workflow Test
on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'release-*' || github.event.pull_request.base.ref == 'fix-*' }} 
    steps:
      - run: echo "Hello, World!"
