name: Example Workflow
on:
  push:
    branches:
      - '*'
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name
        run: |
          echo "Triggered branch: ${{github.ref_name}}"          
