name : Pull Request Workflow
on: 
  pull_request:
    branches:
      - 'release-*'
      - 'fix-*'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo "Hello, World!"
