name: Regex debug
on: workflow_dispatch
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug alias
        run: |
          # alias="> Success! https://40f56fef.onlineexpress-t-beta.jerrdan.com now points to https://nx-phtd7bsnc-advanced-digital-solutions.vercel.app [622ms]"
          alias="> Assigning alias JDID-126.onlineexpress-t-beta.jerrdan.com to deployment nx-l3ewc8hq1-advanced-digital-solutions.vercel.app
            Fetching domain JDID-126.onlineexpress-t-beta.jerrdan.com under advanced-digital-solutions"
          alias_short=$(echo "$text" | awk '{print $4}')
          echo "Alias: $alias_short"
