name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      foo : ${{ github.event.inputs.configuration }} 
    steps:
      - name: Print Configuration
        run : echo " Value is $foo"
      - if: ${{ github.event.inputs.configuration }}
        run: echo "Hello World"
      - if: ${{ !github.event.inputs.configuration }}
        run : echo "Nothing"
     
        
