name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        required: true
        default: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Configuration
        if: ${{ github.event.inputs.configuration }}
        run: echo "Hello World"
      - name : Print Configuration second
        if: ${{ !github.event.inputs.configuration }}
        run : echo "Nothing"
     
        
