name: Reusable Workflow
on : 
  workflow_call:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false
    outputs:
      test:
        description: "The first output string"
        value: ${{ jobs.job1.outputs.output1 }}
      test1:
        description: "The second output string"
        value: ${{ jobs.job1.outputs.output2 }}
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test1 }}
    steps:
      - id: step1
        if : ${{github.event.inputs.configuration == 'true'}}
        run: echo "test=hello world true" >> "$GITHUB_OUTPUT"
      - id: step2
        if : ${{github.event.inputs.configuration == 'false'}}
        run: echo "test1=hello world false" >> "$GITHUB_OUTPUT"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.job1.outputs.output1}}
  #         OUTPUT2: ${{needs.job1.outputs.output2}}
  #       run: echo "This is output $OUTPUT1 $OUTPUT2"
