name : Call a reusable workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  job1:
    uses: ./.github/workflows/ReusableWorkflow1.yml
    with:
      configuration: ${{ inputs.configuration }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.printoutput}}
        run: echo "$OUTPUT1"
