name : Call a reusable workflow
on:
  workflow_dispatch:
    inputs:
      push_configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  job1:
    uses: ./.github/workflows/ReusableWorkflow1.yml
    with:
      configuration: ${{ inputs.push_configuration }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run : echo ${{needs.job1.outputs.my-output}}
