name: Reusable Workflow
on:
  workflow_call:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  # job1:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - with:
  #         configuration-path: ${{ inputs.configuration}}
     

  hello-world:
    runs-on: ubuntu-latest
    # needs: job1
    # uses: ./.github/workflows/Reusableworkflowww.yml
    # with:
    #   config-path: .github/labeler.yml
    # env:
      # foo : ${{ github.event.inputs.configuration }} 
      # foo : $configuration-path 
    outputs:
      my-output: ${{ steps.my-step.outputs.my-output }}
    steps:
      - name: Print Configuration
        id: my-step
        run : |
           if [[ ${{ github.event.inputs.configuration  == 'true' }} ]]; then
            run: echo "my-output = Hello World True" >> $GITHUB_OUTPUT
           else
            run: echo "my-output = Hello World False" >> $GITHUB_OUTPUT
           fi
      # - if: ${{ github.event.inputs.configuration  == 'true' }}
      #   run: echo "my-output = Hello World True" >> $GITHUB_OUTPUT
      # - if: ${{ github.event.inputs.configuration  == 'false' }}
      #   run : echo "my-output = Hello World False" >> $GITHUB_OUTPUT
