name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      foo : ${{ github.event.inputs.configuration }} 
    steps:
      - name: Print Configuration
      - if: ${{ github.event.inputs.configuration  == 'true' }}
        run: echo "Hello World True"
      - if: ${{ github.event.inputs.configuration  == 'false' }}
        run : echo "Hello World False"
     
        
