name: Reusable Workflow
on:
  workflow_call:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false
    outputs:
      first_word:
        value: ${{jobs.hello-world.outputs.output1}}

jobs:  
  hello-world:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.my-step.outputs.first_word }}
    steps:
      - name: Print Configuration
        id: my-step
        run : |
           if ${{ inputs.configuration  == 'true' }}; then
             echo "first_word = Hello World True" >> $GITHUB_OUTPUT
           else
             echo "first_word = Hello World False" >> $GITHUB_OUTPUT
           fi
