name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        required: true
        default: false
        type: bool

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Configuration
        run : |
          if ${{github.event.inputs.configuration}}; then
            echo "Hello World"
          # if ${{github.event.inputs.configuration}} == false
          #   echo " I can't say anything"
        
