name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: True Condition
      - if: ${{ github.event.inputs.configuration  == 'true' }}
        run: echo "Hello World True"
      - name : False condition
      - if: ${{ github.event.inputs.configuration  == 'false' }}
        run : echo "Hello World False"
     
        
