name: Reusable Workflow
on:
  workflow_call:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false
    outputs:
      first_word:
        value: ${{jobs.hello-world.outputs.printoutput}}

jobs:
  # job1:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - with:
  #         configuration-path: ${{ inputs.configuration}}
     

  hello-world:
    runs-on: ubuntu-latest
    # needs: job1
    # uses: ./.github/workflows/Reusableworkflowww.yml
    # with:
    #   config-path: .github/labeler.yml
    # env:
      # foo : ${{ github.event.inputs.configuration }} 
      # foo : $configuration-path 
    outputs:
      printoutput: ${{ steps.my-step.outputs.Trueoutput }}
    steps:
      - name: Print Configuration
        id: my-step
        run : |
           if [[ ${{ github.event.inputs.configuration  == 'true' }} ]]; then
             echo "Trueoutput = Hello World True" >> $GITHUB_OUTPUT
           else
             echo "Trueoutput = Hello World False" >> $GITHUB_OUTPUT
           fi
      # - if: ${{ github.event.inputs.configuration  == 'true' }}
      #   run: echo "my-output = Hello World True" >> $GITHUB_OUTPUT
      # - if: ${{ github.event.inputs.configuration  == 'false' }}
      #   run : echo "my-output = Hello World False" >> $GITHUB_OUTPUT
