name : Call a reusable workflow
on:
  workflow_call:

jobs:
  job1:
    uses: ./.github/workflows/ReusableWorkflow1.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run : echo ${{needs.job1.outputs.my-output}}
