name: Reusable Workflow
on:
  workflow_call:
    inputs:
      configuration:
        description: 'Boolean configuration '
        type: boolean
        required: true
        default: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      foo : ${{ github.event.inputs.configuration }} 
    outputs:
      my-output: ${{ steps.my-step.outputs.my-output }}
    steps:
      - with:
          configuration-path: ${{ inputs.configuration}}
      - name: Print Configuration
        id: my-step
        run : echo " Value is $foo and $configuration-path"
      - if: ${{ github.event.inputs.configuration  == 'true' }}
        run: echo "my-output = Hello World True" >> $GITHUB_OUTPUT
      - if: ${{ github.event.inputs.configuration  == 'false' }}
        run : echo "my-output = Hello World False" >> $GITHUB_OUTPUT
