name : Call a reusable workflow
on:
  workflow_dispatch:
jobs:
  caller_job:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/ReusableWorkflow1.yml
        with:
          configuration: ${{ inputs.configuration }}
      - name: Print output
        run: echo ${{ needs.example_job.outputs.output1 }}
