name: Endeca Deploy ETL
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
          - 'PROD'
          - 'ubuntu-latest'
        default : 'dev'

run-name: Endeca Deploy ETL trial - ${{ inputs.environment }}

jobs:
  build-and-deploy:
    runs-on: [ "${{ (inputs.environment == 'DEV' && 'dev') || (inputs.environment == 'UBUNTU-LATEST' && 'ubuntu-latest') ||  'prod' }}" ]
    steps:
      - name: Dummy workflow
        id: run-name
        run: |
          echo "${{ inputs.environment }}"
          # echo "${{ inputs.environment.toUpperCase() }}"
          output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "runName=$output" >> "$GITHUB_OUTPUT"
          echo "Dummy workflow"
          # output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')

        
