name: Run-Name
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
    && format('DEV')
    || format('TEST') }}
on:
  workflow_dispatch:
  push:
  
jobs:
  Run-Name:
    runs-on: ubuntu-latest
    steps:
      - name: DEV step
        run: echo "DEV"
        
      - name: TEST step
        run: echo "TEST"
