name: Endeca Deploy ETL
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'dev'
          - 'test'
          - 'prod'
          - 'ubuntu-latest'
        default : 'dev'
        
jobs:
  build-and-deploy:
    # runs-on: [self-hosted, X64, Linux, endeca, rhel8, "${{ inputs.environment }}" ]
    runs-on: [ "${{ inputs.environment }}"]
    steps:
      - name: Dummy workflow
        run: |
          output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo $output
          echo "Dummy workflow"

run-name: Endeca Deploy ETL trial - ${{ inputs.environment }}

        
