name: Endeca Deploy ETL
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'DEV'
          - 'TEST'
          - 'PROD'
          - 'UBUNTU-LATEST'
        default : 'dev'

run-name: "Endeca Deploy ETL trial - ${{ inputs.environment }}"
  # ${{ inputs.environment == 'ubuntu-latest' && "Endeca Deploy ETL trial - UBUNTU-LATEST" }}
        
jobs:
  build-and-deploy:
    runs-on: [ "${{ (inputs.environment == 'DEV' && 'dev') || (inputs.environment == 'UBUNTU-LATEST' && 'ubuntu-latest') ||  'prod' }}" ]
    outputs: 
      JOB-OUTPUT: ${{ steps.run-name.outputs.runName }}
    steps:
      - name: Dummy workflow
        id: run-name
        run: |
          output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "runName=$output" >> "$GITHUB_OUTPUT"
          echo "Dummy workflow"
          # output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          # if [[ ${{ github.event.repository.name }} == "ci-systems" ]]; then
          #   My Regression tests: ${{ inputs.my_version }} + ci-systems: ${{ github.head_ref || github.ref_name }}
          # else
          #   My Regression tests: ${{ inputs.my_version }}


        
