name: Run-Name
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
    && format('DEV')
    || github.event_name == 'push'
      && format('TEST')
    || (github.event_name == 'schedule' && (
        startsWith(github.event.schedule, '45 8')
        || startsWith(github.event.schedule, '55 8'))
      && format('TEST-SCHEDULE'))
    || (github.event_name == 'schedule' && startsWith(github.event.schedule, '10 9')
      && format('PROD-SCHEDULE')) }}

# run-name: >-
#   ${{ github.event_name == 'workflow_dispatch'
#     && format('DEV')
#     || (github.event_name == 'schedule' && (
#         startsWith(github.event.schedule, '30 6-23/3')
#         || startsWith(github.event.schedule, '30 0-4/3'))
#       && format('TEST'))
#     || (github.event_name == 'schedule' && startsWith(github.event.schedule, '0 3')
#       && format('PROD')) }}

# run-name: >-
#   ${{ github.event_name == 'workflow_dispatch'
#     && format('DEV')
#     || format('TEST') }}


on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '15 10 * * *'   # TEST
    - cron: '05 10 * * *'   # TEST
    - cron: '30 10 * * *'   # PROD
  
jobs:
  Run-Name:
    runs-on: ubuntu-latest
    steps:
      - name: DEV step
        run: echo "DEV"
        
      - name: TEST step
        run: echo "TEST"
