name: Endeca Deploy ETL
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the environment
        options:
          - 'dev'
          - 'test'
          - 'prod'
          - 'ubuntu-latest'
        default : 'dev'
        
jobs:
  build-and-deploy:
    # runs-on: [self-hosted, X64, Linux, endeca, rhel8, "${{ inputs.environment }}" ]
    runs-on: [ "${{ inputs.environment }}"]
    outputs: 
      JOB-OUTPUT: ${{ steps.run-name.outputs.runName }}
    steps:
      - name: Dummy workflow
        id: run-name
        run: |
          output=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')
          echo "runName=$output" >> "$GITHUB_OUTPUT"
          echo "Dummy workflow"

run-name: Endeca Deploy ETL trial - ${{ needs.build-and-deploy.outputs.JOB-OUTPUT }}

        
