name: Run-Name
run-name: DEV 
on:
  workflow_dispatch:
  push:
  
jobs:
  Run-Name:
    runs-on: ubuntu-latest
    steps:
      - name: DEV step
        run: echo "DEV"
        
      - name: TEST step
        run: echo "TEST"
