name: Schedule trigger
run-name: Schedule
on:
  schedule:
    - cron: '35 15 * * *'   # DEV
    - cron: '0 22 * * *'   # TEST
    - cron: '0 23 * * *'   # PROD

jobs:
  dev_job:
    name: DEV Environment
    if: github.event_name == 'schedule' && startsWith(github.event.schedule, '35 15')
    runs-on: ubuntu-latest
    steps:
      - name: First Step for DEV
        run: echo "This is the first step for DEV"

  test_job:
    name: TEST Environment
    if: github.event_name == 'schedule' && startsWith(github.event.schedule, '0 22')
    runs-on: ubuntu-latest
    steps:
      - name: Second Step for TEST
        run: echo "This is the second step for TEST"

  prod_job:
    name: PROD Environment
    if: github.event_name == 'schedule' && startsWith(github.event.schedule, '0 23')
    runs-on: ubuntu-latest
    steps:
      - name: Third Step for PROD
        run: echo "This is the third step for PROD"
