name: Schedule trigger
run-name: Schedule
on: 
  schedule:
    - cron: '35 15 * * *'   # DEV
    - cron: '10 14 * * *'   # TEST
    - cron: '20 14 * * *'   # TEST
    - cron: '25 14 * * *'   # PROD

jobs:
  dev_job:
    name: DEV Environment
    if: github.event_name == 'schedule' && startsWith(github.event.schedule, '35 15')
    runs-on: ubuntu-latest
    steps:
      - name: First Step for DEV
        run: echo "This is the first step for DEV"

  test_job:
    name: TEST Environment
    if: github.event_name == 'schedule' && (startsWith(github.event.schedule, '10 14') || startsWith(github.event.schedule, '20 14'))
    runs-on: ubuntu-latest
    steps:
      - name: Second Step for TEST
        run: echo "This is the second step for TEST"

  prod_job:
    name: PROD Environment
    if: github.event_name == 'schedule' && startsWith(github.event.schedule, '25 14')
    runs-on: ubuntu-latest
    steps:
      - name: Third Step for PROD
        run: echo "This is the third step for PROD"
