name: Schedule trigger
on:
  schedule:
    - cron: '* * * * *'
    # - cron: '53 11 * * *' # 5:30 PM every day
jobs:
  schedule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [Testing, ole]
    environment: ${{ matrix.os }}
    steps:
      - name: Dummy job
        run: echo "Dummy step"
