name: slack-test
on: workflow_dispatch
jobs:
  slack-job-1:
    runs-on: ubuntu-latest
    steps:
       - name: Run slack job 1
         run: |
           echo "Running slack job 1"
           exit 1

  deploy-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy job 1
        run: echo "Deploy job"

  slack-job-2:
    runs-on: ubuntu-latest
    needs: [slack-job-1, deploy-job-1]
    steps:
       - name: Run slack job 2
         run: |
           echo "Running slack job 2"
           exit 1
         
  deploy-job-2:
    runs-on: ubuntu-latest
    needs: [deploy-job-1]
    steps:
      - name: Run deploy 2
        run: echo "Deploy job"
