name: Status-Check1
on:
  pull_request:
    types:
    - opened
    - reopened
  # workflow_dispatch:
  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Running dummy job
      run: |
        echo "Running first_job"
        exit 1
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Checking whether first job passed or failed or skipped
        run: echo "${{ needs.first_job.result }}"
