name: steps-result-if-else
on: workflow_dispatch
jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: first-step
        run: |
          echo "Hello World"
          exit 1

      - name: Second step
        id: second-step
        run: |
          echo "Hello World"
          exit 1

      - name: Third Step
        id: third-step
        run: |
          echo "Hello World"
          exit 1

      - name: Result step
        id: result-step
        if: always()
        run: |
          declare -a failed_array=()
          echo "First step outcome ${{ steps.first-step.outcome }}"
          echo "second step outcome ${{ steps.second-step.outcome }}"
          if [[ '${{ steps.first-step.outcome }}' == 'failure' ]]; then
            # echo "FAILED_STEP=first-step" >> $GITHUB_OUTPUT 
            failed_array+=("First step")
          fi
          if [[ ${{ steps.second-step.outcome }} == 'failure' || ${{ steps.second-step.outcome }} == 'skipped' ]]; then
            # echo "FAILED_STEP=second-step" >> $GITHUB_OUTPUT 
            failed_array+=("Second step")
          fi
          if [[ ${{ steps.third-step.outcome }} == 'failure' || ${{ steps.third-step.outcome }} == 'skipped' ]]; then
            # echo "FAILED_STEP=third-step" >> $GITHUB_OUTPUT 
            failed_array+=("Third step")
          fi
          echo "Updated array: ${failed_array[@]}"
          echo "FAILED_STEPS=${failed_array[@]}" >> $GITHUB_OUTPUT

      - name: Output of failed step
        if: always()
        run: |  
          echo "${{steps.result-step.outputs.FAILED_STEPS}}"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Hello World"

  slack-job-cancelled-1:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Write
        run: |
          SHORT_SHA='78eaf67d' >> $GITHUB_ENV
          echo "Hello World UNit test"
          
  slack-job-cancelled-2:
    runs-on: ubuntu-latest
    needs: [e2etest]
    if: always()
    steps:
      - name: Write
        run: |
          echo "${{ env.SHORT_SHA }}"
          echo "Hello World e2e test"
