name: Get Step URL
on: workflow_dispatch
jobs:
  getURL:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello"
      - name: Step 2
        run: echo "World"
      - name: Step 3
        run: exit 1
      - name: Get URL
        if: failure()
        run: |
          # echo "Failed step URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#${{ github.job }}/${{ github.step }}"
          # echo "Failed step occurred in job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#${{ github.job }}/${{ github.run_number }}"
          echo "Failed step occurred in job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.run_number }}"

  getResult:  
    runs-on: ubuntu-latest
    steps:
      - name: Run something
        run: echo "Run something"
          
        
