name: Get Step URL
on: workflow_dispatch
jobs:
  getURL:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello"
      - name: Step 2
        run: echo "World"
      - name: Step 3
        run: exit 1
      - name: Run always
        id: get-job-id
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          echo $jobs
          # job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          job_id=$(echo "$jobs" | grep -oP '"id":\K\d+' | head -1)
          echo "job_id is: $job_id"
          echo "job_id=$job_id" >> $GITHUB_OUTPUT
          
          # jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          # job_id=$(echo "$jobs" | grep -oP '(?<="id":")[^"]*(?=","runner_name":"${{ runner.name }}")')
          # echo "job_id is: $job_id"
          # echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: Get URL
        if: failure()
        run: |
          echo Job ID: ${{ steps.get-job-id.outputs.job_id }}
          # echo "Failed step URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#${{ github.job }}/${{ github.step }}"
          # echo "Failed step occurred in job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#${{ github.job }}/${{ github.run_number }}"
          echo "Failed step occurred in job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}"

  getResult:  
    runs-on: ubuntu-latest
    steps:
      - name: Run something
        run: echo "Run something"

  dummyJob:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: echo "Hello world"
    
          
        
