name: steps-result-if-else
on: workflow_dispatch
jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: first-step
        run: echo "Hello World"

      - name: Second step
        id: second-step
        run: |
          echo "Hello World"
          exit 1

      - name: Result step
        id: result-step
        if: always()
        run: |
          echo "First step outcome ${{ steps.first-step.outcome }}"
          echo "second step outcome ${{ steps.second-step.outcome }}"
          if [[ ${{ steps.first-step.outcome }} == 'failure' ]]; then
            echo "FAILED_STEP=first-step" >> "$GITHUB_OUTPUT"
          else
            echo "FAILED_STEP=second-step" >> "$GITHUB_OUTPUT"
          fi
          echo $FAILED_STEP

      - name: Output of failed step
        if: always()
        run: |  
          echo "${{steps.result-step.outptus.FAILED_STEP}}"
