name: steps-result-if-else
on: workflow_dispatch
jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: first-step
        run: echo "Hello World"

      - name: Second step
        id: second-step
        run: echo "Hello World"

  result-job:
    runs-on: ubuntu-latest
    needs: [e2etest]
    steps:
      - name: Result job
        if: always() 
        run: |
          echo "Hello World"
