name: steps-result-if-else
on: 
  push
jobs:
  e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        id: first-step
        run: |
          echo "Hello World"
          echo "Change the commimt message this time it will change"

      - name: Second step
        id: second-step
        run: |
          echo "Hello World"
          exit 1

      - name: Third Step
        id: third-step
        run: |
          echo "Hello World"
          exit 1

      - name: Result step
        id: result-step
        if: always()
        run: |
          declare -a failed_array=()
          echo "First step outcome ${{ steps.first-step.outcome }}"
          echo "second step outcome ${{ steps.second-step.outcome }}"
          if [[ '${{ steps.first-step.outcome }}' == 'failure' ]]; then
            # echo "FAILED_STEP=first-step" >> $GITHUB_OUTPUT 
            failed_array+=("First step")
          fi
          if [[ ${{ steps.second-step.outcome }} == 'failure' || ${{ steps.second-step.outcome }} == 'skipped' ]]; then
            # echo "FAILED_STEP=second-step" >> $GITHUB_OUTPUT 
            failed_array+=("Second step")
          fi
          if [[ ${{ steps.third-step.outcome }} == 'failure' || ${{ steps.third-step.outcome }} == 'skipped' ]]; then
            # echo "FAILED_STEP=third-step" >> $GITHUB_OUTPUT 
            failed_array+=("Third step")
          fi
          echo "Updated array: ${failed_array[@]}"
          echo "FAILED_STEPS=${failed_array[@]}" >> $GITHUB_OUTPUT

      - name: Output of failed step
        if: always()
        run: |  
          echo "${{steps.result-step.outputs.FAILED_STEPS}}"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "Hello World"

  slack-job-cancelled-1:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Write
        run: |
          echo SHORT_SHA='78eaf67d' >> $GITHUB_ENV
          echo "Hello World UNit test"
          
      - name: Write ENV
        run: echo "${{ env.SHORT_SHA }}"
          
  slack-job-cancelled-2:
    runs-on: ubuntu-latest
    needs: [slack-job-cancelled-1]
    if: always()
    steps:
      - name: Write
        run: |
          echo "${{ env.SHORT_SHA }}"
          echo "Hello World e2e test"

  DateandTime:
    runs-on: ubuntu-latest
    steps: 
      - name: Write Date
        id: set_datetime
        run: |
          current_date_time=$(date +"%d %b at %l:%M %p")
          echo "Current date and time: $current_date_time"
          echo "Setting triggered_datetime..."
          triggered_datetime=$(date '+%Y-%m-%d %H:%M:%S')
          echo $triggered_datetime

      - name: Get current date
        id: date
        run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
        
      - name: Write output date and commit message
        run: |
          echo ${{ steps.date.outputs.TODAY_DATE }}
          echo ${{ github.event.head_commit.message }}

      - name: Write message for final time
        if: always()
        run: |
          message="${{ github.event.head_commit.message }}"
          extracted_message=$(echo "$message" | sed 's/\(Signed-off\).*/\1/')
          echo "Extracted message: $extracted_message"
          echo "COMMIT_MESSAGE=$extracted_message" >> "$GITHUB_OUTPUT"

      - name: Extract commit message
        id: commit-message
        if: always()
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }} 
        run: |
          npm install @actions/core
          node - <<EOF
            const core = require('@actions/core');
            const message = process.env.COMMIT_MESSAGE;
            console.log('Before message: ', message);
            const result = message.split('Signed-off-by:')[0].trim();
            console.log('After message: ', result);
          EOF 
          
      - name: Asia india timing
        run: |
          export TZ="Asia/Kolkata"
          # Get the current time in IST
          ist_time=$(date +"%Y-%m-%d %H:%M:%S %Z")
          # Print the current time in IST
          echo "Current time in IST: $ist_time"
