name: Strategy Matrix
run-name: Strategy matrix 
on: workflow_dispatch
jobs:
  Test-Strategy:
    strategy:
      matrix:
        os: [1, 2, 3]
    runs-on: [ubuntu-latest, "${{ matrix.runner == 3 && 'windows-latest' || matrix.runner }}" ]
    # runs-on: [ubuntu-latest, "${{ matrix.runner == 3 && 'windows-latest' || 'matrix.runner' }}"]
    steps:
      - name: Print the OS
        run: |
          echo "Matrix is : ${{ matrix.os }}"
