name: Learn Strategy
on: workflow_dispatch
jobs:
 learn:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        version: [10, 12, 14]
   steps:
     - name: Build and deploy
       run: |
         echo "Let this be dummy build job"
     - name: Write numbers
       run: |
         echo "Hello ${{ matrix.version }}"
