name: Nightwatch Test Summary


on: workflow_dispatch


jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '14.x'


      - name: Install Dependencies
        run: npm install


      - name: Run Nightwatch Tests
        run: npm run nightwatch


      - name: Save Test Results
        run: mv path/to/test-results.xml $GITHUB_WORKSPACE/test-results.xml


      - name: Write Test Summary
        run: |
          const { JUnitReportBuilder } = require('junit-report-builder');
          const fs = require('fs');


          const builder = new JUnitReportBuilder();
          builder.parseFiles(['test-results.xml']);
          const testResults = builder.getTestResults();


          // Process testResults and write summary
          const summary = `Total Tests: ${testResults.tests}, Passed: ${testResults.tests - testResults.failures - testResults.errors}, Failed: ${testResults.failures}, Errors: ${testResults.errors}`;


          fs.writeFileSync('test-summary.txt', summary);
          echo "$summary"
