name: Test echo Workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Locate test.txt
        run: |
          config_file='test.txt'
          echo "Cypress config file: $config_file"
          if [ -z "$config_file" ]; then
            echo "Test txt/ file not found"
            exit 1
          fi
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          commit_alias=${BRANCH_NAME}.onlineexpress-t-beta.jerrdan.com
          echo "Branch Name:$BRANCH_NAME"
          echo "$BRANCH_NAME"
          echo "Commit alias is: $commit_alias"
          echo "$commit_alias"
          echo "Opening file"
          commit_alias=$(cat $config_file)
          echo "$commit_alias"
          sed -i "s|baseUrl: 'https://onlineexpress-t.jlg.com'|baseUrl: '$commit_alias'|g" "$CONFIG_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name 'Shivam Srivastava'
          git config --global user.email 'shivamvkas18@gmail.com'
          git add "$CONFIG_FILE"
          git commit -m "Update base URL in cypress.config.ts"
          git push
