name: Test echo Workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Locate test.txt
        run: |
          # config_file=$(find . -name "ab.txt" -type f)
          config_file='test.txt'
          echo "Cypress config file: $config_file"
          if [ -z "$config_file" ]; then
            echo "Test txt/ file not found"
            exit 1
          fi
          export CONFIG_FILE="$config_file"
      - name: Test echo
        id: commit-alias
        run: |
           BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
           commit_alias=${BRANCH_NAME}.onlineexpress-t-beta.jerrdan.com
           echo "Branch Name:"
           echo "$BRANCH_NAME"
           echo "Commit alias is"
           echo "$commit_alias"
           
      - name: Replace base URL
        run: |
          # Replace the base URL with the commit alias
          # commit_alias=$(cat GITHUB_OUTPUT)
          cat test.txt
          commit_alias=$(cat test.txt)
          sed -i "s|baseUrl: 'https://onlineexpress-t.jlg.com'|baseUrl: '$commit_alias'|g" "$CONFIG_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name 'Shivam Srivastava'
          git config --global user.email 'shivamvkas18@gmail.com'
          git add "$CONFIG_FILE"
          git commit -m "Update base URL in cypress.config.ts"
          git push
